# Generated by Django 5.2 on 2025-05-14 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='catalog.products')),
            ],
            options={
                'db_table': 'view_history',
                'ordering': ['-viewed_at'],
                'unique_together': {('user_id', 'product')},
            },
        ),
    ]
