# Generated by Django 5.2 on 2025-06-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productinventory'),
    ]

    operations = [
    ]
