# Generated by Django 5.2 on 2025-06-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20250602_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
    ]
