# Generated by Django 5.2 on 2025-06-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_orders_comment_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='comment',
        ),
    ]
