# Generated by Django 5.2 on 2025-06-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_orders_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
