# Generated by Django 5.2 on 2025-06-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0008_orders_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.creditcard'),
        ),
    ]
