# Generated by Django 5.2 on 2025-06-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0009_orders_card_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='card_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.creditcard'),
        ),
    ]
