# Generated by Django 5.2 on 2025-06-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_favorites_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
    ]
