# Generated by Django 5.2 on 2025-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('number', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'credit_cards',
            },
        ),
    ]
